network="dev"
miner-enabled=true
miner-coinbase="0xfe3b557e8fb62b89f4916b721be55ceb828dbd73"
rpc-http-cors-origins=["all"]
host-allowlist=["*"]
rpc-ws-enabled=true
rpc-http-enabled=true
data-path="./tmpdata-path"
rpc-http-port=7545
rpc-ws-port=7546
p2p-port=20202
min-gas-price=0