/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ATokensAndRatesHelperInterface extends ethers.utils.Interface {
  functions: {
    "configureReserves(address[],uint256[],uint256[],uint256[],uint256[],bool[])": FunctionFragment;
    "initDeployment(address[],string[],uint256[6][],address,address)": FunctionFragment;
    "initReserve(address[],address[],address[],address[],uint8[])": FunctionFragment;
    "owner()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "configureReserves",
    values: [
      string[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      BigNumberish[],
      boolean[]
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initDeployment",
    values: [
      string[],
      string[],
      [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ][],
      string,
      string
    ]
  ): string;
  encodeFunctionData(
    functionFragment: "initReserve",
    values: [string[], string[], string[], string[], BigNumberish[]]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "configureReserves",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initDeployment",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "initReserve",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "deployedContracts(address,address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "deployedContracts"): EventFragment;
}

export class ATokensAndRatesHelper extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ATokensAndRatesHelperInterface;

  functions: {
    configureReserves(
      assets: string[],
      baseLTVs: BigNumberish[],
      liquidationThresholds: BigNumberish[],
      liquidationBonuses: BigNumberish[],
      reserveFactors: BigNumberish[],
      stableBorrowingEnabled: boolean[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "configureReserves(address[],uint256[],uint256[],uint256[],uint256[],bool[])"(
      assets: string[],
      baseLTVs: BigNumberish[],
      liquidationThresholds: BigNumberish[],
      liquidationBonuses: BigNumberish[],
      reserveFactors: BigNumberish[],
      stableBorrowingEnabled: boolean[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initDeployment(
      assets: string[],
      symbols: string[],
      rates: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ][],
      treasuryAddress: string,
      incentivesController: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initDeployment(address[],string[],uint256[6][],address,address)"(
      assets: string[],
      symbols: string[],
      rates: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ][],
      treasuryAddress: string,
      incentivesController: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    initReserve(
      stables: string[],
      variables: string[],
      aTokens: string[],
      strategies: string[],
      reserveDecimals: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "initReserve(address[],address[],address[],address[],uint8[])"(
      stables: string[],
      variables: string[],
      aTokens: string[],
      strategies: string[],
      reserveDecimals: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  configureReserves(
    assets: string[],
    baseLTVs: BigNumberish[],
    liquidationThresholds: BigNumberish[],
    liquidationBonuses: BigNumberish[],
    reserveFactors: BigNumberish[],
    stableBorrowingEnabled: boolean[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "configureReserves(address[],uint256[],uint256[],uint256[],uint256[],bool[])"(
    assets: string[],
    baseLTVs: BigNumberish[],
    liquidationThresholds: BigNumberish[],
    liquidationBonuses: BigNumberish[],
    reserveFactors: BigNumberish[],
    stableBorrowingEnabled: boolean[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initDeployment(
    assets: string[],
    symbols: string[],
    rates: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ][],
    treasuryAddress: string,
    incentivesController: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initDeployment(address[],string[],uint256[6][],address,address)"(
    assets: string[],
    symbols: string[],
    rates: [
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish,
      BigNumberish
    ][],
    treasuryAddress: string,
    incentivesController: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  initReserve(
    stables: string[],
    variables: string[],
    aTokens: string[],
    strategies: string[],
    reserveDecimals: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "initReserve(address[],address[],address[],address[],uint8[])"(
    stables: string[],
    variables: string[],
    aTokens: string[],
    strategies: string[],
    reserveDecimals: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    configureReserves(
      assets: string[],
      baseLTVs: BigNumberish[],
      liquidationThresholds: BigNumberish[],
      liquidationBonuses: BigNumberish[],
      reserveFactors: BigNumberish[],
      stableBorrowingEnabled: boolean[],
      overrides?: CallOverrides
    ): Promise<void>;

    "configureReserves(address[],uint256[],uint256[],uint256[],uint256[],bool[])"(
      assets: string[],
      baseLTVs: BigNumberish[],
      liquidationThresholds: BigNumberish[],
      liquidationBonuses: BigNumberish[],
      reserveFactors: BigNumberish[],
      stableBorrowingEnabled: boolean[],
      overrides?: CallOverrides
    ): Promise<void>;

    initDeployment(
      assets: string[],
      symbols: string[],
      rates: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ][],
      treasuryAddress: string,
      incentivesController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "initDeployment(address[],string[],uint256[6][],address,address)"(
      assets: string[],
      symbols: string[],
      rates: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ][],
      treasuryAddress: string,
      incentivesController: string,
      overrides?: CallOverrides
    ): Promise<void>;

    initReserve(
      stables: string[],
      variables: string[],
      aTokens: string[],
      strategies: string[],
      reserveDecimals: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "initReserve(address[],address[],address[],address[],uint8[])"(
      stables: string[],
      variables: string[],
      aTokens: string[],
      strategies: string[],
      reserveDecimals: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    deployedContracts(aToken: null, strategy: null): EventFilter;
  };

  estimateGas: {
    configureReserves(
      assets: string[],
      baseLTVs: BigNumberish[],
      liquidationThresholds: BigNumberish[],
      liquidationBonuses: BigNumberish[],
      reserveFactors: BigNumberish[],
      stableBorrowingEnabled: boolean[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "configureReserves(address[],uint256[],uint256[],uint256[],uint256[],bool[])"(
      assets: string[],
      baseLTVs: BigNumberish[],
      liquidationThresholds: BigNumberish[],
      liquidationBonuses: BigNumberish[],
      reserveFactors: BigNumberish[],
      stableBorrowingEnabled: boolean[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    initDeployment(
      assets: string[],
      symbols: string[],
      rates: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ][],
      treasuryAddress: string,
      incentivesController: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initDeployment(address[],string[],uint256[6][],address,address)"(
      assets: string[],
      symbols: string[],
      rates: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ][],
      treasuryAddress: string,
      incentivesController: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    initReserve(
      stables: string[],
      variables: string[],
      aTokens: string[],
      strategies: string[],
      reserveDecimals: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "initReserve(address[],address[],address[],address[],uint8[])"(
      stables: string[],
      variables: string[],
      aTokens: string[],
      strategies: string[],
      reserveDecimals: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    configureReserves(
      assets: string[],
      baseLTVs: BigNumberish[],
      liquidationThresholds: BigNumberish[],
      liquidationBonuses: BigNumberish[],
      reserveFactors: BigNumberish[],
      stableBorrowingEnabled: boolean[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "configureReserves(address[],uint256[],uint256[],uint256[],uint256[],bool[])"(
      assets: string[],
      baseLTVs: BigNumberish[],
      liquidationThresholds: BigNumberish[],
      liquidationBonuses: BigNumberish[],
      reserveFactors: BigNumberish[],
      stableBorrowingEnabled: boolean[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initDeployment(
      assets: string[],
      symbols: string[],
      rates: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ][],
      treasuryAddress: string,
      incentivesController: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initDeployment(address[],string[],uint256[6][],address,address)"(
      assets: string[],
      symbols: string[],
      rates: [
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish,
        BigNumberish
      ][],
      treasuryAddress: string,
      incentivesController: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    initReserve(
      stables: string[],
      variables: string[],
      aTokens: string[],
      strategies: string[],
      reserveDecimals: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "initReserve(address[],address[],address[],address[],uint8[])"(
      stables: string[],
      variables: string[],
      aTokens: string[],
      strategies: string[],
      reserveDecimals: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
